export let weathercodes = {
  0: "clear sky",
  1: "mainly clear",
  2: "partly cloudy",
  3: "overcast",
  45: "fog",
  48: "depositing rime fog",
  51: "light drizzle",
  53: "moderate drizzle",
  55: "dense intensity drizzle",
  56: "light freezing drizzle",
  57: "dense intensity freezing drizzle",
  61: "slight rain",
  63: "moderate rain",
  65: "heavy intensity rain",
  66: "light freezing rain",
  67: "heavy intensity rain",
  71: "slight snow fall",
  73: "moderate snow fall",
  75: "heavy intensity snow fall",
  77: "snow grains",
  80: "slight rain showers",
  81: "moderate rain showers",
  82: "violent rain showers",
  85: "slight snow showers",
  86: "heavy snow showers",
  95: "thunderstorm",
  96: "thunderstorm with slight hail",
  99: "thunderstorm with heavy hail",
};
